name: mr_squirrel_android
description: "Mr Squirrel - Aplikasi operasional warung kelontong."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3

  # Navigation
  go_router: ^17.3.0

  # Local database
  drift: ^2.33.0
  drift_flutter: ^0.3.0
  sqlite3_flutter_libs: ^0.6.0

  # Utilities
  uuid: ^4.5.3
  intl: ^0.20.3

  # Supabase — remote sync data source (Phase 7+)
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.15.1
  drift_dev: ^2.33.0
  riverpod_generator: ^4.0.4

flutter:
  uses-material-design: true
